---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hcp-create-secrets
  namespace: hcp
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "update", "patch"]
