# This role binding allows "hcp" ServiceAccount to create
# secrets in the "hcp" namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hcp-create-secrets
  namespace: hcp
subjects:
- kind: ServiceAccount
  name: hcp
  namespace: hcp
roleRef:
  kind: Role
  name: hcp-create-secrets 
  apiGroup: rbac.authorization.k8s.io
