apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: allow-apiserver-external-access
  namespace: kube-system
spec:
  selector:
    matchExpressions:
    # TODO: find a better key...
    # This will apply this preset to any Pod created by a Deployment.
    # fine for now (11/07/19)
    - key: pod-template-hash
      operator: Exists
  env:
  # Set this to the DNS name which resolves to the public IP of the ingress controller
  # in your "control plane cluster" so the traffic will be routed to the apiserver
  # running in a namespace based on the SNI
  - name: KUBERNETES_SERVICE_HOST
    value: "hcp.v2.platform9.beer"
  - name: KUBERNETES_SERVICE_PORT
    value: "443"
